var express = require('express')
  , bodyParser = require('body-parser')
  ;

var app = express();

/*! Handle YAML in request bodies */
app.use(bodyParser.text({type: 'text/yaml'}));

/*! View the implied YAML config */
app.post('/api/v1/inspect/config', require('./handlers/inspect-config'));

/*! View the CloudFormation template generated by YAML */
app.post('/api/v1/inspect/template', require('./handlers/inspect-template'));

/*! Create or update stack :name with the YAML from the body */
app.put('/api/v1/stacks/:name', require('./handlers/deploy-stack'));

/*! Delete stack :name if it exists */
app.delete('/api/v1/stacks/:name', require('./handlers/delete-stack'));

/*! Run express server */
var server = app.listen(3000, function(){
  var host = server.address().address
    , port = server.address().port
    ;

  console.log(
    'hird.io listening on http://%s:%s',
    host,
    port
  );
});
